# -*- coding: utf-8 -*-
"""Assignment. Alan Syed Muhammed S

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1las30E2Cs6cbKZmlfkCfbiH3yYgmUGXu
"""

#1. > Making an Acronym Generater
 
userinput= (input("Enter your text "))
text = userinput.split()
a = ''
for i in text:
    a = a+(i[0]).upper()
print(a)

"""In the above code, I am first taking a string user input. Then, the split() function in Python is used to split the sentence. Later declared, a new variable ‘a’ to store the acronym of a phrase.
In the end, I am running a for loop over the variable ‘text’, which represents the split of user input. While running the for loop, we store the index value of str [0] of every word after a split and turn it into an uppercase format using the upper() function.
"""

#2.> story teller.....!
import random
when = ['A few years ago', 'Yesterday', 'Last night', 'A long time ago','On 20th Jan']
who = ['a rabbit', 'an elephant', 'a mouse', 'a turtle','a cat']
name = ['Ali', 'Miriam','daniel', 'Hoouk', 'Starwalker']
residence = ['Barcelona','India', 'Germany', 'Venice', 'England']
went = ['cinema', 'university','seminar', 'school', 'laundry']
happened = ['made a lot of friends','Eats a burger', 'found a secret key', 'solved a mistery', 'wrote a book']
print(random.choice(when) + ', ' + random.choice(who) +', named ' +
      random.choice(name),'that lived in '+random.choice(residence)+
      ',went to the '+random.choice(went)+' and '+random.choice(happened))

"""I tried to generate a random story every time the user runs the program. For this, first stored the parts of the stories in different lists, then the Random module can be used to select the random parts of the story stored in different lists. Random module is imported and then created parts of the stories in different lists, Then played  the print statements (which are the variables of  lists) at random to generate a random story.

"""

#3 >password creator

import random
pas=''
s="abcdefghijk"
a="1234567890"
l='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
M='!@#$%^&*()?'
for i in range(3):
 p = random.choice(s)
 pas=pas+p
 p = random.choice(l)
 pas=pas+p
 p = random.choice(M)
 pas=pas+p 
 p = random.choice(a)
 pas=pas+p 
print(pas[0:8])



"""For generating a strong password creator, I used random module. Then assigned 4 variables named [s, a, l, M] which represents small letters, numbers, capital letters, and symbols respectively. Then used "for loop" for getting the random variables for 2 times and also "pas=pas+p" for concatenation. Then used slicing at 8th position for getting a password of length 8. Then printed the "pas". Your password generator is ready..!"""

#4 > Programme to find the area of a triangle 
import math
a= float(input('enter first side '))
b= float(input('enter second side '))
c= float(input('enter third side '))
s=((a+b+c))/2
r=s*((s-a)*(s-b)*(s-c))
area= math.sqrt(r)
print ("Area =",area)
#print(s)

"""To find the area of the triangle with 3 sides , using “herolds formula”. First I assigned three variables which are user input in nature. Then used “.math” module for finding the square root for the "r" variable which consist of other variables as follows:
#r=s((s-a)(s-b)*(s-c))
#area= math.sqrt(r)
Then printed (area)



"""

#5 > Celsius to Farenheit Converter
celsius = float (input (' Temperature value in degree Celsius:'))
fahrenheit = (celsius * 1.8) + 32
print(str(celsius )+ " degree Celsius is equal to " + str(fahrenheit )+ " degree Fahrenheit.")

"""The code helps the conversion formula from Celsius to Fahrenheit and displays the final output. The relationship between the 
Fahrenheit scale and the Celsius scale is given by :
Fahrenheit=(Celsius∗1.8)+32


"""